#!/usr/bin/env sh

yabai -m config layout bsp

yabai -m config window_placement second_child

yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

yabai -m config split_ratio 0.50

yabai -m config auto_balance on

yabai -m config focus_follows_mouse autofocus

yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Finder" manage=off


